### ISSUE TITLE
Not working in MIUI / Android 12

### ISSUE THREAD

**Issue by garygreen** [SimonMarquis/SleepTimer#11]
The tile shows and it starts counting down to sleep - when it reaches the time the volume DOES turn down to zero, but then a second or so later it restores back to existing volume.

I'm not sure if this is a MIUI or Android 12 incompatibility issue. I was testing with two different audio sources playing from:

- Youtube (background playback)
- Musicolet (simple music player, using System audio decoder)

Both experience same issue, it works momentarily but then restores volume.

**Comment by SimonMarquis** [comment]
This is the expected behavior:
https://github.com/SimonMarquis/SleepTimer/blob/f62a208079fa61cdaa8a086ab33e192624b45362/app/src/main/java/fr/smarquis/sleeptimer/SleepAudioService.kt#L42-L45

This ensure the volume is reset to the initial value, otherwise, alarms or other apps/notifications could be silenced...

What should happen between lowering the volume to 0 and restoring the inital value is the playback being paused.
Is this not working on your device?

**Comment by garygreen** [comment]
> Is this not working on your device?

Yes exactly. It lowers the volume slowly... then goes to zero. But the music in Youtube or Musicolet isn't paused, so when volume is restored the music carries on playing.

**Comment by garygreen** [comment]
Also just tested in Twitch app, same issue.

**Comment by SimonMarquis** [comment]
I've tested this on multiple apps (Youtube, YoutubeMusic, Twitch, etc.), and the music/video stream is correctly paused.
This might be an issue with your OS not respecting audio focus requests.
I've just published a 1.2 version where the delay to restore the initial volume has been increased.
This might help with this issue, but otherwise I won't be able to fix this.

**Comment by SimonMarquis** [comment]
I'll close this issue as it should have been fixed by the last update.
