### ISSUE TITLE
Tile icon blurred

### ISSUE THREAD

**Issue by baroca** [SimonMarquis/SleepTimer#15]
The functionality is working as expected. Great work!
I'm however, seeing a problem in the tile icon.

![photo1685370617(1)](https://github.com/SimonMarquis/SleepTimer/assets/2146876/cd6a2abd-ef16-4ea0-87c4-ac1c8803ef0b)

It happens both in dark and white theme.
I'm using Oneplus 8 Pro on OxygenOS 13

**Comment by SimonMarquis** [comment]
@baroca, this is probably because your OS does not handle Android Vector Drawable with an intrinsic size of 1dp*1dp:
https://github.com/SimonMarquis/SleepTimer/blob/f32eb6d6e1e447802b58fb590779eb81408c28fa/app/src/main/res/drawable/ic_tile.xml#L2-L3

I've created the following PR: #16
Could you test the generated APK and tell me if this fixes it on your device https://github.com/SimonMarquis/SleepTimer/actions/runs/5114091852#artifacts

**Comment by baroca** [comment]
It's indeed fixed now. Thank you!
Let me know if you need anymore tests.

**Comment by SimonMarquis** [comment]
I'll try to publish it very soon, thanks for the report.

**Comment by SimonMarquis** [comment]
Release 1.2.1 is ready, I've sent it to Google Play.
https://github.com/SimonMarquis/SleepTimer/releases/tag/1.2.1
