### ISSUE TITLE
Sleep timer does not stop playback with bluetooth connected.

### ISSUE THREAD

**Issue by darnrain** [SimonMarquis/SleepTimer#5]
Hello I wanted to say that you have made a very useful app. The only problem I found is when I connect my Bluetooth headset, set sleep timer for 1:30 to sleep. The sleep timer does not stop playback of music. But if I don't use Bluetooth headset then sleep timer does stop playback of my music. I tried this two different nights, on the nights I didn't use Bluetooth it worked and the nights I did use Bluetooth it just keeps playing all night. 

I am running Oreo 8.0 lgv20 H910 rooted. Let me know if you need more info?

**Comment by SimonMarquis** [comment]
Hi @darnrain, I've tried it on my Bose QC35 and it works as expected.
Can you verify your headset is registered as a media device in the Bluetooth settings

![Screenshot_20210630-202206.png](https://user-images.githubusercontent.com/1921278/124012192-2a91cf80-d9e1-11eb-9054-2ad529a7ee48.png)

And media audio is enabled

![Screenshot_20210630-202451.png](https://user-images.githubusercontent.com/1921278/124012288-4bf2bb80-d9e1-11eb-96e0-19a4127b6ec6.png)

Otherwise, it might be an incompatibility with how media sound is handled on your OS.

**Comment by darnrain** [comment]
Yeah it is I will take some photos. I have not tried with with any other Bluetooth headset. Maybe it's an issue with Oreo 8.0 I will keep playing round with it trying another Bluetooth headset. Now I do have a wireless controller paired also but not in use at the same time. I could try removing that.

I just set the timer for 10 mutinies with Bluetooth headset going to see what it will do.

![Screenshot_2021-06-30-11-36-53](https://user-images.githubusercontent.com/60840489/124014315-373e0580-d998-11eb-9654-395dbda07a88.png)
![Screenshot_2021-06-30-11-36-58](https://user-images.githubusercontent.com/60840489/124014324-39a05f80-d998-11eb-948e-a8defeb661a4.png)

**Comment by darnrain** [comment]
Well after 10 minutes the music paused when playing on Bluetooth. But when I was using it I set the sleep timer to 1:30 hr's the music never paused on Bluetooth. That's why I thought it was the Bluetooth headset. You think the OS is killing the app in the background? Should I set Power savings exclusions on the sleep timer? And try again?
