### ISSUE TITLE
App tile unresponsive

### ISSUE THREAD

**Issue by Nowye** [SimonMarquis/SleepTimer#8]
Clicking on the app's tile doesn't seem to work

**Comment by SimonMarquis** [comment]
Unfortunately, Quick Settings Tiles are very finicky and sometimes appears as "Unavailable" and unresponsive.
A single tap on it should force the system to refresh it.
Also, make sure you did not set any battery restriction on it in the settings app.
I hope it will fix itself, because I can't fix Android quirks. 😜

**Comment by Nowye** [comment]
> Also, make sure you did not set any battery restriction on it in the settings app.

This seems to be the problem for me. It works now. Thank you very much!
